parameters:
#    yinshine_page.example.class: Yinshine\PageBundle\Example

services:
#    yinshine_page.example:
#        class: %yinshine_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  # yinshine_page.menu_builder:
  #   class: Yinshine\PageBundle\Menu\Builder
  #   arguments: ["@knp_menu.factory"]
  # yinshine_page.menu.main:
  #   class: Knp\Menu\MenuItem
  #   factory_service: yinshine_page.menu_builder
  #   factory_method: mainMenu
  #   arguments: ["@request"]
  #   scope: request
  #   tags:
  #     - { name: knp_menu.menu, alias: main }
